### ISSUE TITLE
Add interop metric to lanes' schema 

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Reporting-App#149]
The list of interop metric is stored in CR628.
It will be stored in the lanes endpoint as follow:
```yaml
lanes:
    interop:
        metric1: float
        metric2: float
        metric3: float
````
