### ISSUE TITLE
analysis_driver_proc stage updates fail in concurrent threads

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Reporting-App#21]
In, e.g, genotype validation (which runs in another thread), the `patch` on the proc fails with a mismatching `_etag`.

Instead of having an embedded list, we should have a separate `stages` endpoint. This way, different stages can be modified concurrently.

**Comment by mwhamgenomics** [comment]
We might want a generic endpoint called 'events', so we can record review dates, etc. In this case, the schema might look like:

``` yaml
stages:
    stage_id: {type: 'string', unique: true}  # run_150723_startdate_stagename
    events: {type: 'list', schema: {type: 'string', data_relation: {resource: 'events', field: 'event_id', embeddable: true}}
    stage_name: {type: 'string'} 
    exit_status: {type: 'integer'}

events:
    event_id: {type: 'string', unique: true}
    event_date: {type: 'datetime'}
    event_type: {type: 'string'}  # e.g. 'stage start', 'run_review'
    description: {type: 'string'}  # e.g. 'bcl2fastq', 'pass'
    comments: {type: 'multilinestring'}
```
